### PR TITLE
Code cleanup 

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Hi @johnff - I'm evaluating this extension for our needs- this was written against old CiviCRM versions so I'm just bringing  it up to date & doing some cleanup as I dig into it.

Note I upped the version to 5.18 which is what I'm testing  on  - that means any future releases would be for that version + but obviously you have the existing version for anyone using it on an older version. There are a  few deprecated  functions in there   which  I'll fix up as I look but it  needs to be able to assume  a recent version to do that.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Also despite comments in the readme - I can't see where code  / ui for  the search action mentioned

**Comment by davidknoll** [comment]
Hi @eileenmcnaughton ,
I'm afraid John doesn't work at FF any more and we moved away from Civi a few years ago, so this extension is no longer maintained. I've accepted your PR and tagged a release though. John's upstream release seems to have had some more attention in the years in-between.

**Comment by eileenmcnaughton** [comment]
Oh really - I didn't realise - it can't be that long since I was talking about his beds for homeless project with him!

**Comment by davidknoll** [comment]
That's a separate organisation, not connected to FF, but he was using Civi.

**Comment by eileenmcnaughton** [comment]
Ah right - are you going to Barcelona?

**Comment by eileenmcnaughton** [comment]
I actually did a bunch more PRs against @johnff's repo as I realised that was ahead in the end - are you still using this extension?

**Comment by davidknoll** [comment]
I can't speak for John, but we at FF aren't using Civi at all any more, so my answer to both questions is no.

**Comment by eileenmcnaughton** [comment]
Ah ok -  we'll  miss you:-)

**Pull request merged**
